spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttanulim
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/ttanulim
          username: postgres
          password: 1234
    show-sql: false

server:
  port: 8080
